apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: taskmanager
data:
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "taskmanager"
  DB_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: taskmanager
type: Opaque
stringData:
  DB_PASSWORD: "postgres"   # change this for real deployments
